### ISSUE TITLE
使用导出dll 导出函数调用 OcrDestroy 会触发一个异常，

### ISSUE THREAD

**Issue by xpston008** [RapidAI/RapidOcrOnnxLibTest#1]
**测试vs2019、vs2015 都会触发一个异常。**

**1.下载onnxruntime-1.12.1-vs2019-static-md.7z 
          opencv-4.6.0-windows-vs2019-md.7z

2. [RapidOcrOnnx](https://github.com/RapidAI/RapidOcrOnnx) 编译，选择多线程 DLL (/MD) 模式。**

#include <iostream>
#include "OcrLiteCApi.h"
#include <Windows.h>

typedef OCR_HANDLE(*__Onnx_OcrInit)(const char* szDetModel, const char* szClsModel, const char* szRecModel, const char* szKeyPath, int nThreads);
typedef OCR_BOOL(*__Onnx_OcrDetectEx)(OCR_HANDLE handle, const char* imgPath, const char* imgName, OCR_PARAM* pParam);
typedef void(*__Onnx_OcrDestroy)(OCR_HANDLE handle);

extern  __Onnx_OcrInit      _Onnx_OcrInit = NULL;
extern  __Onnx_OcrDetectEx  _Onnx_OcrDetect = NULL;
extern  __Onnx_OcrDestroy   _Onnx_OcrDestroy = NULL;

void LoadOnnx()
{
	HMODULE hlib = LoadLibraryA("RapidOcrOnnx.dll");
	_Onnx_OcrInit = (__Onnx_OcrInit)GetProcAddress(hlib, "OcrInit");
	_Onnx_OcrDetect = (__Onnx_OcrDetectEx)GetProcAddress(hlib, "OcrDetect");
	_Onnx_OcrDestroy = (__Onnx_OcrDestroy)GetProcAddress(hlib, "OcrDestroy");

	printf("%u\n", _Onnx_OcrDestroy);
}

int main(int argc, char** argv)
{
	LoadOnnx();
	const char* szDetModel = "C:\\Users\\admin\\Desktop\\onnxruntime\\RapidOcrOnnx-main\\TextApi\\Release\\models\\ch_PP-OCRv3_det_infer.onnx";
	const char* szClsModel = "C:\\Users\\admin\\Desktop\\onnxruntime\\RapidOcrOnnx-main\\TextApi\\Release\\models\\ch_ppocr_mobile_v2.0_cls_infer.onnx";
	const char* szRecModel = "C:\\Users\\admin\\Desktop\\onnxruntime\\RapidOcrOnnx-main\\TextApi\\Release\\models\\ch_PP-OCRv3_rec_infer.onnx";
	const char* szKeyPath =  "C:\\Users\\admin\\Desktop\\onnxruntime\\RapidOcrOnnx-main\\TextApi\\Release\\models\\ppocr_keys_v1.txt";
	OCR_HANDLE handle = _Onnx_OcrInit(szDetModel, szClsModel, szRecModel, szKeyPath, 4);
	OCR_PARAM Param;
	Param.padding = 50;
	Param.maxSideLen = 1024;
	Param.boxScoreThresh = 0.6f;
	Param.boxThresh = 0.3f;
	Param.unClipRatio = 2.0f;
	Param.doAngle = 1;
	Param.mostAngle = 1;
	_Onnx_OcrDetect(handle, "C:\\Users\\admin\\Desktop\\onnxruntime\\RapidOcrOnnx-main\\TextApi\\Release\\", "1.bmp", &Param); //调用正常。
	_Onnx_OcrDestroy(handle); // 这里会引发异常  “TextApi.exe 已触发了一个断点。”
	return 0;
}###

**Comment by benjaminwan** [comment]
1. 下载范例项目工程自带的dll是Release版，不能用于调试运行
2. 更新了v1.1.3版，修复了一些问题，增加了调试运行说明

**Comment by xpston008** [comment]
@benjaminwan  我清楚的你的意思。
  直接执行，调用清理函数OcrDestroy(handle)，还是会卡一段时间。
  RapidOcrOnnx.exe 在OcrDestroy(handle)亦是如此。

**Comment by benjaminwan** [comment]
v1.1.3 RapidOcrOnnx有修复scoreToTextLine索引越界问题（但这个问题在BaiPiaoOcrOnnx就存在）
v1.1.3还改了~析构方法里的
inputNames.clear();
outputNames.clear();
BaiPiaoOcrOnn和v1.1.2这里是用free()，这个应该没有影响吧。

其余的代码就跟旧版BaiPiaoOcrOnn一样了，剩下的不同就是引用的onnxruntime和opencv版本改变了。

你可以用v1.1.3再试试，如果还是有差别，那基本可以认为是onnxruntime和opencv的改变引起的。

**Comment by xpston008** [comment]
谢谢！
inputNames.clear();
outputNames.clear();
v1.13不出现问题了。


CAPI使用dll导出函数，需要选择静态运行库(多线程 DLL(/MD)才行，不然std::string 析构有问题。
发出来给后来者遇到问题解决

**Comment by benjaminwan** [comment]
v1.1.3虽然修复了索引越界，但空格会识别错误。
v1.2.0版已发布。
在linux下用valgrind测了，还是得用free()方法，所以1.2.0又加回去了，只是在windows平台换成了专用的_aligned_free()。

**Comment by xpston008** [comment]
好的。谢谢。明天编译v1.2.0，

使用vs2019 多线程 DLL(/Md)编译出来动态库.使用vs2015导出函数。
1.在win10开发环境，加载onnx模型时正常。移植到win7(x86-32位）系统，加载onnx模型时，就出现错误。测试vs2019 编译出来RapidOcrOnnx.exe，在win7（x86-32位） 正常运行。

目测三个模型加载onnxruntime，都使用抛出异常的编码方式。但dll 里面无法捕获异常，一旦捕获异常直接挂掉了。

不知道什么原因。如知道请告知一二，谢谢

**Comment by benjaminwan** [comment]
@xpston008 看着挺晕的，不知道我理解的对不对，在exe里用try-catch可以起作用，但却无法对dll起作用，是这个意思吧？
这似乎与vs版本没有关系，默认win调用dll就是如此。

[使用try catch内部防止C++ DLL异常](https://stackoverflow.com/questions/5951987/prevent-c-dll-exception-using-try-catch-internally)
这里提到 try.catch在默认情况下不会捕捉到调用异常，因为默认的异常处理模型只捕捉同步异常，而调用异常是异步异常。
如果项目设置，使用/EHa而不是/EHsc，那么try.catch就可以捕捉到。

我在macOS试了一下，在RapidOcrOnnx中添加throw Ort::Exception("test error!", static_cast<OrtErrorCode>(-2));
编译成dll，放到RapidOcrOnnxLibTest中调用
```
try {
        OCR_HANDLE handle = OcrInit(DET_MODEL, CLS_MODEL, REC_MODEL, KEY_FILE, THREAD_NUM);
        OCR_PARAM param = {0};
        OCR_BOOL bRet = OcrDetect(handle, DEFAULT_IMG_PATH, DEFAULT_IMG_NAME, &param);
        if (bRet) {
            int nLen = OcrGetLen(handle);
            if (nLen > 0) {
                char *szInfo = (char *) malloc(nLen);
                if (szInfo) {
                    if (OcrGetResult(handle, szInfo, nLen)) {
                        printf("%s", szInfo);
                    }
                    free(szInfo);
                }
            }
        }
        if (handle) {
            OcrDestroy(handle);
        }
        if (!handle) {
            printf("cannot initialize the OCR Engine.\n");
            return -1;
        }
    }
    catch (std::exception &e) {
        printf("error=%s\n", e.what());
    }
    return 0;
```
最后终端输出error=test error!，exe没有蹦

**Comment by xpston008** [comment]
@benjaminwan 

抱歉！一下子想表达多个问题。没有描述好
是的异常捕获：外部捕获过异常，确实可以捕获到的。

**其实我想问主要是：**
环境：
1. [x86 **RapidOcrOnnx.dll**  和 **RapidOcrOnnx.exe** ]编译环境 win7+ vs2019   多线程 DLL(/Md)
2. 在win10 vs2015 x86 导出 RapidOcrOnnx.dll 函数，生成**Test.exe**

问题：
**Test.exe** 在**win10**开发环境 OcrInit加载模型正常。
**Test.exe** 移植到**win7 32**位系统OcrInit加载模型失败,但RapidOcrOnnx.exe 在这win7系统可以正常运行。

**Comment by benjaminwan** [comment]
没有条件试win7 32位系统

我用win10 vs2019编译出的x86 libTest，放到win7 64位上是可以跑的。

只能做一些猜测。
1. 32位系统可用内存太少，导致初始化出错。
2. 路径斜杠与反斜杠的问题。代码是跨平台的统一用/，但win一般是用\，虽然win10没问题，但不知道老系统会不会有问题。

**Comment by xpston008** [comment]
@benjaminwan  
modepath =''
路径中，中文会惹起问题，不知道是什么编码。不知道是否需要去转为utf8，传入才行。

**Comment by benjaminwan** [comment]
win用wchar,wstring

**Comment by xpston008** [comment]
std::wstring strToWstr(std::string str) {
#ifdef WIN32
    if (str.length() == 0)
        return L"";
    int len = MultiByteToWideChar(CP_ACP, 0, str.c_str(), -1, NULL, 0);
    std::wstring wstr(len, L'\0');
    MultiByteToWideChar(CP_ACP, 0, str.c_str(), -1, (wchar_t*)wstr.c_str(), len);
    return wstr;
 #endif;
    return L"";
}
把函数修改成这样，就可以正常传入中文路径了。
